### ISSUE TITLE
add structured (JSON/XML) output

### ISSUE THREAD

**Issue by prusnak** [google/bloaty#53]
... so one can post-process the results using scripts/tools. Parsing text results is suboptimal.

Even just disabling the use of abbreviations (e.g. 8.31Ki) via an option would help tremendously.

When this is possible one can create a visual output similar to this:

![baobab](https://wiki.gnome.org/Apps/Baobab?action=AttachFile&do=get&target=screenshot.png)

**Comment by carbontwelve** [comment]
This would certainly make this tool useful for piping into a tracking service.

**Comment by haberman** [comment]
Yes this seems worthwhile! The main concern is making the output format (whatever it is) stable over the long-term, so that any tools that people write don't break.

I'd definitely prefer JSON over XML. YAJL (via the [yajl_gen API](http://lloyd.github.io/yajl/yajl-2.0.1/yajl__gen_8h.html) seems promising, as YAJL is small and simple.

**Comment by haberman** [comment]
Actually I'm thinking the simplest thing might just be CSV output. No extra library would be required.

**Comment by haberman** [comment]
There is CSV output now. I'd love to see whatever visualizations you come up with!
