### ISSUE TITLE
What is [Unmapped] when using symbols/cppsymbols?

### ISSUE THREAD

**Issue by parbo** [google/bloaty#73]
A large chunk of my binary is [Unmapped] when using cppsymbols, how do I dig further into that?

**Comment by haberman** [comment]
It's a good question. There are lots of parts of your binary that aren't part of the program code or data itself: debug information, symbol tables, unwind information, etc. You can dig more into this by using `-d cppsymbols,sections`.

I'm considering making `-d cppsymbols` dig deeper, so that any parts of the binary that are not literally part of certain symbols but are *directly used* by those symbols will show up.

**Comment by parbo** [comment]
In this case I was already looking at `-d sections,cppsymbols` and the `[Unmapped]` showed up in the `.text` section. Having it dig deeper sounds very nice though!

**Comment by haberman** [comment]
Try rebuilding from head and see what you think. I just submitted a bunch of changes that make "symbols" and "compileunits" go much deeper! compileunits should now cover almost all of the binary, without seeing `[Unmapped]`.

**Comment by haberman** [comment]
This coverage has greatly improved (there is very little `[Unmapped]` any more), so I'm going to resolve this issue now.
